### Upload an image for OCR processing
POST http://localhost:8080/api/ocr
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="UCB_2.JPG"
Content-Type: image/jpeg

< ./src/main/resources/img/UCB_2.JPG
--WebAppBoundary--


### Upload another image for OCR processing
POST http://localhost:8080/api/ocr
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="testPic.jpg"
Content-Type: image/jpeg

< ./src/main/resources/img/testPic.jpg
--WebAppBoundary--

### Upload an invalid file (not an image)
POST http://localhost:8080/api/ocr
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="invalid_file.txt"
Content-Type: text/plain

< ./src/main/resources/img/invalid_file.txt
--WebAppBoundary--